packages:
  - apps/*
  - packages/*

catalog:
  '@types/debug': ^4.1.12
  '@types/node': ^22
  '@types/react': 19.1.2
  '@types/react-dom': 19.1.2
  dotenv-cli: ^7.4.4
  next: 16.0.7
  radix-ui: 1.4.2
  react: 19.2.0
  react-dom: 19.2.0
  tsx: ^4.20.5
  typescript: ^5.9.2
  zod: ^4.1.8
