// from a URL hash generated by React Router `#/hof?_k=5563cq`
// return the path to be passed to React Rouer hashHistory.push methd `/hof`
function getUrl(hash) {
  const array = /#(\/.*)\?.*/.exec(hash)
  return array.length === 2 ? array[1] : ''
}

export default function (win) {
  const key = 'bestofjs_url'
  return {
    save() {
      const url = getUrl(win.location.hash)
      win.localStorage.setItem(key, url)
    },
    get(resetUrl) {
      const url = win.localStorage[key]
      if (resetUrl) this.reset()
      return url
    },
    reset() {
      win.localStorage.removeItem(key)
    }
  }
}
