name: "Shared setup"
description: "Set up Node.js with PNPM"

runs:
  using: composite
  steps:
    - name: Install PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 9.4.0

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
