name: "Install"
description: "Sets up Node.js with PNPM and installs depedencies"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install PNPM
      uses: pnpm/action-setup@v3
      with:
        version: 8.9.0

    - name: Install Dependencies
      shell: bash
      run: pnpm install
