const fs = require('fs-extra')
const path = require('path')
const prettyBytes = require('pretty-bytes')

/**
 * Return the content of the HTML template used to generate server-side generated pages
 * Don't use the file inside the `public` folder, we need the one generated by `react-scripts build` command
 * that includes a link to the css file `main.<hash>.css`
 */
export function readHtmlTemplate() {
  const filepath = path.resolve(process.cwd(), 'build', 'index.html')
  return fs.readFile(filepath, 'utf8')
}

export function writeHtmlFile({ html, pathname }) {
  const filepath = path.resolve(process.cwd(), 'build', pathname, 'index.html')
  return fs
    .outputFile(filepath, html)
    .then(() => `${filepath} file created (${prettyBytes(html.length)})`)
}
