name: Update GitHub Data
on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level: 3 => info, 4 => debug"
        required: true
        default: 3
        type: choice
        options:
          - 3
          - 4
      limit:
        description: "Number of projects to process (mainly for debugging, keep the default value of 0 to process everything)"
        required: false
        type: number
        default: 0
      skip:
        description: "Number of projects to skip (when paginating)"
        required: false
        type: number
        default: 0
      concurrency:
        description: "Number of projects to process concurrently"
        required: false
        type: number
        default: 1
      throttleInterval:
        description: "Interval in milliseconds to wait between requests, to avoid rate limit errors"
        required: false
        type: number
        default: 750
env:
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  # caution: `GITHUB_` is not a valid prefix for secrets!
  GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  API_TRIGGER_BUILD_WEBHOOK_URL: ${{ secrets.API_TRIGGER_BUILD_WEBHOOK_URL }}
jobs:
  update-github-data:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/tooling/github-actions/install
      - name: Install Dependencies
        shell: bash
        run: pnpm install -F backend...
      - name: Update GitHub Data and take snapshots
        run: pnpm -F backend daily-update-github-data --loglevel ${{ inputs.logLevel || 3 }} --limit ${{ inputs.limit || 0 }} --skip ${{ inputs.skip || 0 }} --concurrency ${{ inputs.concurrency || 1 }} --throttleInterval ${{ inputs.throttleInterval || 750 }}
      - name: Send Webhook to Vercel
        run: pnpm -F backend trigger-build-static-api
