name: Update Package Data
on:
  schedule:
    - cron: "00 1 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level: 3 => info, 4 => debug"
        required: true
        default: 3
        type: choice
        options:
          - 3
          - 4
      limit:
        description: "Number of projects to process (mainly for debugging, keep the default value of 0 to process everything)"
        required: false
        type: number
        default: 0
      skip:
        description: "Number of projects to skip (when paginating)"
        required: false
        type: number
        default: 0
      concurrency:
        description: "Number of projects to process concurrently"
        required: false
        type: number
        default: 1
      throttleInterval:
        description: "Interval in milliseconds to wait between requests, to avoid rate limit errors"
        required: false
        type: number
        default: 0
env:
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
jobs:
  update-package-data:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/tooling/github-actions/install
      - name: Install Dependencies
        shell: bash
        run: pnpm -F backend install
      - name: Update Packages Data
        run: pnpm -F backend daily-update-package-data --loglevel ${{ inputs.logLevel || 3 }} --limit ${{ inputs.limit || 0 }} --skip ${{ inputs.skip || 0 }} --concurrency ${{ inputs.concurrency || 5 }} --throttleInterval ${{ inputs.throttleInterval || 0 }}
