name: Update Bundle Size
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level: 3 => info, 4 => debug"
        required: true
        default: 3
        type: choice
        options:
          - 3
          - 4
      limit:
        description: "Number of projects to process (mainly for debugging, keep the default value of 0 to process everything)"
        required: false
        type: number
        default: 0
      skip:
        description: "Number of projects to skip (when paginating)"
        required: false
        type: number
        default: 0
      concurrency:
        description: "Number of projects to process concurrently"
        required: false
        type: number
        default: 1
env:
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
jobs:
  update-bundle-size:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/tooling/github-actions/install
      - name: Install Dependencies
        shell: bash
        run: pnpm -F backend... install
      - name: Update Bundle Size
        run: pnpm -F backend daily-update-bundle-size --loglevel ${{ inputs.logLevel || 3 }} --limit ${{ inputs.limit || 0 }} --skip ${{ inputs.skip || 0 }} --concurrency ${{ inputs.concurrency || 1 }}
